schedule_tracker/schedule_tracker/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from tasks.api_views import TaskViewSet
from schedules.api_views import ScheduleViewSet

router = DefaultRouter()
router.register(r'tasks', TaskViewSet)
router.register(r'schedules', ScheduleViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('schedules/', include('schedules.urls')),
    ## rest_api用のルーティング
    path('api/', include(router.urls))
]

schedule_tracker/tasks/urls.py
from django.urls import path

app_name = 'tasks'
from .views import task_index_view, task_register_view, task_update_view, task_delete_view

urlpatterns = [
    path('', task_index_view,name='index'),
    path('register', task_register_view,name="register"),
    path('update/<int:pk>', task_update_view, name="update"),
    path('delete/<int:pk>', task_delete_view, name="delete")
    # TODO: スケジュール一覧へ遷移するためのルーティング
]

schedule_tracker/tasks/models.py
from django.db import models
from django.db.models import CharField
from django.template.defaultfilters import length


# Create your models here.
class Task(models.Model):
    STATUS_CHOICES = [
        ("0", "todo"),
        ("1", "doing"),
        ("2", "done")
    ]
    title = models.CharField(verbose_name="タスク名",max_length=50)
    description = models.TextField(verbose_name="説明（任意）",max_length=200,blank=True)
    due_date = models.DateField(verbose_name="期限",)
    status = models.CharField(verbose_name="進捗状況", choices=STATUS_CHOICES, default='0')
    created_at = models.DateTimeField(verbose_name="作成日",auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.title

schedule_tracker/tasks/forms.py
from django import forms

from .models import Task

class TaskRegisterForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "due_date","status"]

schedule_tracker/tasks/views.py
from datetime import datetime,date
from django.shortcuts import render,redirect
from django.db.models import Q

from django.views import View

from .models import Task
from .forms import TaskRegisterForm

# Create your views here.
class TaskIndexView(View):
    def get(self, request, *args, **kwargs):
        # templateに渡す値(context)の用意
        context = dict()
        # 登録されているタスク一覧を取得する
        # tasksという名前でcontextに登録
        # 優先順位の高いもの（期日が迫っているもの->進捗状況）の昇順にsort
        context["tasks"] = Task.objects.filter(Q(due_date__gte=datetime.now().date())|Q(status__regex="[01]")).order_by('due_date','status')
        # タスク一覧ページを表示する
        return render(request,"tasks/index.html",context)

task_index_view = TaskIndexView.as_view()

class TaskRegisterView(View):
    def get(self, request, *args, **kwargs):
        context = dict()
        # formという名前でTaskRegisterFormを追加
        context["form"] = TaskRegisterForm()

        return render(request,"tasks/register.html",context)

    def post(self, request, *args, **kwargs):
        # form二送信された値をコピー
        copy = request.POST.copy()

        # statusに初期値を設定する
        copy["status"] = "0"

        #formに送信されたデータを追加
        post_form = TaskRegisterForm(copy)

        # バリデーションエラーのチェック
        if not post_form.is_valid():
            print(post_form.errors)
            print("エラーがあります")
        else:
            # 問題なければformの内容を保存
            post_form.save()

        return redirect("tasks:index")

task_register_view = TaskRegisterView.as_view()

class TaskUpdateView(View):
    def get(self,request,pk,*args, **kwargs):
        # templateに渡す値（context）の用意
        context = dict()
        # idがpkであるタスクをtaskという名前でcontext二格納
        context["task"] = Task.objects.get(id=pk)

        return render(request, "tasks/update.html",context)

    def post(self,request, pk, *args, **kwargs):
        # pkをidにもつtaskの情報を取得
        task = Task.objects.filter(id=pk).first()

        # 送信された情報でtaskの情報を更新する
        post_form = TaskRegisterForm(request.POST,instance=task)

        # バリデーションエラーのチェック
        if not post_form.is_valid():
            print("エラーがあります")
        else:
            # 問題なければformの内容を保存
            post_form.save()

        return redirect("tasks:index")

task_update_view = TaskUpdateView.as_view()

class TaskDeleteView(View):
    def get(self,request, pk,*args, **kwargs):
        context = dict()
        context["task"] = Task.objects.filter(id=pk).first()

        return render(request,"tasks/delete.html",context)

    def post(self,request, pk, *args, **kwargs):
        task = Task.objects.filter(id=pk).first()

        task.delete();

        return redirect("tasks:index")

task_delete_view = TaskDeleteView.as_view()

schedule_tracker/templates/tasks/delete.html
{% load static %}
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>タスク削除</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>
<body>
<header>
    <h1>タスク削除</h1>
</header>
<main>
    <div class="container">
        <table>
            <tr>
                <th class="left_corner">タスク名：</th>
                <td>{{ task.title }}</td>
            </tr>
            <tr>
                <th>説明（任意）：</th>
                <td>{{ task.description }}</td>
            </tr>
            <tr>
                <th>期限：</th>
                <td>{{ task.due_date|date:"Y-m-d" }}</td>
            </tr>
            <tr>
                <th>進捗状況：</th>
                <td>{{task.get_status_display}}</td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="button_group">
                        <form action="{% url 'tasks:delete' task.id %}" method="post">
                            {% csrf_token %}
                            <button class="button delete">
                                <input type="submit" value="削除">
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <button class="button link">
        <a href="{% url 'tasks:index' %}">タスク一覧へ戻る</a>
    </button>
</main>
</body>
</html>

schedule_tracker/templates/tasks/index.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>タスク一覧</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>
<body>

<header>
    <h1>タスク一覧</h1>
    <hr/>
</header>
<main>
    <button class="button link">
        <a href="{% url 'tasks:register' %}">新規作成</a>
    </button>
    <div class="container">
        <table>
            <thead>
            <tr>
                <th class="left_corner">タスク名</th>
                <th>説明</th>
                <th>期限</th>
                <th>進捗状況</th>
                <th>作成日時</th>
                <th>更新日時</th>
                <th>更新</th>
                <th>削除</th>
            </tr>
            </thead>

            {% for task in tasks %}
            <tr>
                <td>{{ task.title }}</td>
                <td>{{task.description}}</td>
                <td>{{task.due_date}}</td>
                <td><span class="status {{ task.get_status_display }}">{{task.get_status_display}}</span></td>
                <td>{{task.created_at}}</td>
                <td>{{task.updated_at}}</td>
                <td><a href="{% url 'tasks:update' task.id %}">更新</a></td>
                <td><a href="{% url 'tasks:delete' task.id %}">削除</a></td>
            </tr>
            {% endfor %}
        </table>

    </div>

</main>
</body>
</html>

schedule_tracker/templates/tasks/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>タスク新規作成</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>
<body>
<header>
    <h1>タスク新規作成</h1>
</header>
<main>
    <div class="container">
        <form action="{% url 'tasks:register' %}" method="post">
            {% csrf_token %}
            {# TODO: ヘッダーの固定 #}
            <table>
                <tr>
                    <th class="left_corner">タスク名：</th>
                    <td>
                        <input name="title" placeholder="タスク名" required size=50 type="text">
                    </td>
                </tr>
                <tr>
                    <th>説明（任意）：</th>
                    <td>
                        <textarea cols=52 name="description" placeholder="タスクの詳細を記入してください"
                                  rows=2></textarea>
                    </td>
                </tr>
                <tr>
                    <th>期限：</th>
                    <td>
                        <input name="due_date" required type="date">
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="button_group">
                            <button class="button register">
                                <input type="submit" value="作成">
                            </button>
                            <button class="button reset">
                                <a href="{% url 'tasks:register' %}">reset</a>
                            </button>
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <button class="button link">
        <a href="{% url 'tasks:index' %}">タスク一覧へ戻る</a>
    </button>
</main>
</body>
</html>

schedule_tracker/templates/tasks/update.html
{% load static %}
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>タスク更新</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>
<body>
<header>
    <h1>タスク更新</h1>
</header>
<main>
    <div class="container">
        <form action="{% url 'tasks:update' task.id %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <th class="left_corner">タスク名：</th>
                    <td>
                        <input name="title" placeholder="タスク名" required size=50 type="text" value={{ task.title }}>
                    </td>
                </tr>
                <tr>
                    <th>説明（任意）：</th>
                    <td>
                        <textarea cols=52 name="description" placeholder="タスクの詳細を記入してください"
                                  rows=2>{{ task.description }}</textarea>
                    </td>
                </tr>
                <tr>
                    <th>期限：</th>
                    <td>
                        <input
                                type="date"
                                name="due_date"
                                required
                                value={{ task.due_date|date:"Y-m-d" }}
                                style="width:100%"
                        >
                    </td>
                </tr>
                <tr>
                    <th>進捗状況：</th>
                    <td>
                        <select name="status" class="status_select">
                            <option value="" selected hidden>{{task.get_status_display}}</option>
                            <option value="0">todo</option>
                            <option value="1">doing</option>
                            <option value="2">done</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="button_group">
                            <button class="button update">
                                <input type="submit" value="更新">
                            </button>
                            <button class="button reset">
                                <a href="{% url 'tasks:update' task.id %}">reset</a>
                            </button>
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <button class="button link">
        <a href="{% url 'tasks:index' %}">タスク一覧へ戻る</a>
    </button>
</main>
</body>
</html>