schedule_tracker/schedule_tracker/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from tasks.api_views import TaskViewSet
from schedules.api_views import ScheduleViewSet

router = DefaultRouter()
router.register(r'tasks', TaskViewSet)
router.register(r'schedules', ScheduleViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('schedules/', include('schedules.urls')),
    ## rest_api用のルーティング
    path('api/', include(router.urls))
]

schedule_tracker/schedules/urls.py
from django.urls import path

app_name = 'schedules'
from .views import schedule_index_view, schedule_register_view, schedule_update_view, schedule_delete_view

urlpatterns = [
    path('', schedule_index_view,name='index'),
    path('register', schedule_register_view,name="register"),
    path('update/<int:pk>', schedule_update_view, name="update"),
    path('delete/<int:pk>', schedule_delete_view, name="delete")
    # TODO: スケジュール一覧へ遷移するためのルーティング
]

schedule_tracker/tasks/urls.py
from django.urls import path

app_name = 'tasks'
from .views import task_index_view, task_register_view, task_update_view, task_delete_view

urlpatterns = [
    path('', task_index_view,name='index'),
    path('register', task_register_view,name="register"),
    path('update/<int:pk>', task_update_view, name="update"),
    path('delete/<int:pk>', task_delete_view, name="delete")
    # TODO: スケジュール一覧へ遷移するためのルーティング
]

schedule_tracker/schedules/models.py
from django.db import models

from datetime import time

from tasks.models import Task

# Create your models here.
class Schedules(models.Model):
    title = models.CharField(verbose_name="スケジュール名",max_length=255)
    date = models.DateField(verbose_name="日付")
    time = models.TimeField(verbose_name="時間",default=time(0,0),blank=True)
    memo = models.TextField(verbose_name="メモ",blank=True)

    task = models.ForeignKey(Task, verbose_name="タスクID", on_delete=models.CASCADE, related_name='schedule')

    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="更新日時", auto_now=True)

    def __str__(self):
        return self.title

schedule_tracker/schedules/forms.py
from django import forms

from .models import Schedules


class ScheduleRegisterForm(forms.ModelForm):
    class Meta:
        model = Schedules
        fields = ["title", "date", "time", "memo", "task"]

schedule_tracker/schedules/views.py
from datetime import datetime, time

from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from tasks.models import Task

from .forms import ScheduleRegisterForm
from .models import Schedules


# Create your views here.
class ScheduleIndexView(View):
    def get(self, request, *args, **kwargs):
        # templateに渡す値(context)の用意
        context = dict()
        # 登録されているタスク一覧を取得する
        # schedulesという名前でcontextに登録
        # 優先順位の高いもの（期日が迫っているもの->進捗状況）の昇順にsort
        context["schedules"] = Schedules.objects.all()
        # タスク一覧ページを表示する
        return render(request, "schedules/index.html", context)


schedule_index_view = ScheduleIndexView.as_view()


class ScheduleRegisterView(View):
    def get(self, request, *args, **kwargs):
        context = dict()
        # formという名前でScheduleRegisterFormを追加
        context["form"] = ScheduleRegisterForm()

        # 登録されているタスク一覧をcontext二格納
        context["tasks"] = Task.objects.filter(Q(due_date__gte=datetime.now().date()) | Q(status__regex="[01]"))

        return render(request, "schedules/register.html", context)

    def post(self, request, *args, **kwargs):
        # 送信されたデータをコピー
        copy = request.POST.copy()

        if (not copy["time"]):
            copy["time"] = time(0, 0)

        # formに送信されたデータを追加
        post_form = ScheduleRegisterForm(copy)

        # バリデーションエラーのチェック
        if not post_form.is_valid():
            print(post_form.errors)
            print("エラーがあります")
        else:
            # 問題なければformの内容を保存
            post_form.save()

        return redirect("schedules:index")


schedule_register_view = ScheduleRegisterView.as_view()


class ScheduleUpdateView(View):
    def get(self, request, pk, *args, **kwargs):
        # 情報を更新したいスケジュールを取得
        # 存在しない場合は404エラーを返す
        schedule = get_object_or_404(Schedules, id=pk)
        tasks = Task.objects.all()

        # idがpkであるタスクをscheduleという名前でcontextに格納
        context = {"schedule": schedule, "tasks": tasks}

        print(type(schedule.time))
        return render(request, "schedules/update.html", context)

    def post(self, request, pk, *args, **kwargs):
        # 情報を更新したいスケジュールを取得
        # 存在しない場合は404エラーを返す
        schedule = get_object_or_404(Schedules, id=pk)

        # 送信された情報でscheduleの情報を更新する
        post_form = ScheduleRegisterForm(request.POST, instance=schedule)

        # バリデーションエラーのチェック
        if not post_form.is_valid():
            print("エラーがあります")
        else:
            # 問題なければformの内容を保存
            post_form.save()

        return redirect("schedules:index")


schedule_update_view = ScheduleUpdateView.as_view()


class ScheduleDeleteView(View):
    def get(self, request, pk, *args, **kwargs):
        # 情報を更新したいスケジュールを取得
        # 存在しない場合は404エラーを返す
        schedule = get_object_or_404(Schedules, id=pk)
        context= {"schedule": schedule}

        return render(request, "schedules/delete.html", context)

    def post(self, request, pk, *args, **kwargs):
        schedule = get_object_or_404(Schedules, id=pk)

        schedule.delete()

        return redirect("schedules:index")


schedule_delete_view = ScheduleDeleteView.as_view()

schedule_tracker/templates/schedules/delete.html
{% load static %}
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>スケジュール削除</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>
<body>
<header>
    <h1>スケジュール削除</h1>
</header>
<main>
    <div class="container">
        <table>
            <tr>
                <th class="left_corner">スケジュール名：</th>
                <td>
                    {{ schedule.title }}
                </td>
            </tr>
            <tr>
                <th>日付：</th>
                <td>
                    {{ schedule.date }}
                </td>
            </tr>
            <tr>
                <th>時間：</th>
                <td>
                    {{ schedule.time }}
                </td>
            </tr>
            <tr>
                <th>タスク名：</th>
                <td>
                    {{ schedule.task.title }}
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <form action="{% url 'schedules:delete' schedule.id %}" method="POST">
                        {% csrf_token %}
                        <div class="button_group">
                            <button class="button delete">
                                <input type="submit" value="削除">
                            </button>
                        </div>
                    </form>
                </td>
            </tr>
        </table>
    </div>
    <button class="button link">
        <a href="{% url 'schedules:index' %}">スケジュール一覧へ戻る</a>
    </button>
</main>
</body>
</html>

schedule_tracker/templates/schedules/index.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>スケジュール一覧</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>
<body>

<header>
    <h1>スケジュール一覧</h1>
    <hr/>
</header>
<main>
    <button class="button link">
        <a href="{% url 'schedules:register' %}">新規作成</a>
    </button>
    <div class="container">
        <table>
            <thead>
            <tr>
                <th class="left_corner">スケジュール名</th>
                <th>日付</th>
                <th>時間</th>
                <th>メモ</th>
                <th>タスク名</th>
                <th>作成日時</th>
                <th>更新日時</th>
                <th>更新</th>
                <th>削除</th>
            </tr>
            </thead>

            {% for schedule in schedules %}
            <tr>
                <td>{{ schedule.title }}</td>
                <td>{{schedule.date}}</td>
                <td>{{schedule.time}}</td>
                <td>{{schedule.memo }}</td>
                <td>{{ schedule.task.title }}</td>
                <td>{{schedule.created_at}}</td>
                <td>{{schedule.updated_at}}</td>
                <td><a href="{% url 'schedules:update' schedule.id %}">更新</a></td>
                <td><a href="{% url 'schedules:delete' schedule.id %}">削除</a></td>
            </tr>
            {% endfor %}
        </table>

    </div>

</main>
</body>
</html>

schedule_tracker/templates/schedules/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>スケジュール新規作成</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>
<body>
<header>
    <h1>スケジュール新規作成</h1>
</header>
<main>
    <div class="container">
        <form action="{% url 'schedules:register' %}" method="post">
            {% csrf_token %}
            {# TODO: ヘッダーの固定 #}
            <table>
                <tr>
                    <th class="left_corner">スケジュール名：</th>
                    <td>
                        <input name="title" placeholder="スケジュール名" required size=50 type="text">
                    </td>
                </tr>
                <tr>
                    <th>日時：</th>
                    <td>
                        <input type="date" name="date" value="日付" required>
                    </td>
                </tr>
                <tr>
                    <th>時間：</th>
                    <td>
                        <input type="time" name="time">
                    </td>
                </tr>
                <tr>
                    <th>メモ：</th>
                    <td>
                        <textarea name="memo" cols=52 rows=2 placeholder="作業内容についての補足など"></textarea>
                    </td>
                </tr>
                <tr>
                    <th>時間：</th>
                    <td>
                        <select name="task">
                            {% for task in tasks %}
                                <option value={{ task.id }}>{{ task.title }} </option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="button_group">
                            <button class="button register">
                                <input type="submit" value="作成">
                            </button>
                            <button class="button reset">
                                <a href="{% url 'schedules:register' %}">reset</a>
                            </button>
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <button class="button link">
        <a href="{% url 'schedules:index' %}">スケジュール一覧へ戻る</a>
    </button>
</main>
</body>
</html>

schedule_tracker/templates/schedules/update.html
{% load static %}
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>スケジュール更新</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
</head>
<body>
<header>
    <h1>スケジュール更新</h1>
</header>
<main>
    <div class="container">
        <form action="{% url 'schedules:update' schedule.id %}" method="post">
            {% csrf_token %}
            {# TODO: ヘッダーの固定 #}
            <table>
                <tr>
                    <th class="left_corner">スケジュール名：</th>
                    <td>
                        <input name="title" placeholder="スケジュール名" required schedule.title size=50 type="text"
                               value={{ schedule.title }}>
                    </td>
                </tr>
                <tr>
                    <th>日時：</th>
                    <td>
                        <input name="date" required schedule.date|date: type="date" value={{ schedule.date|date:"Y-m-d"}}>
                    </td>
                </tr>
                <tr>
                    <th>時間：</th>
                    <td>
                        <input name="time" type="time" value={{ schedule.time|time:"H:i"}}>
                    </td>
                </tr>
                <tr>
                    <th>メモ：</th>
                    <td>
                        <textarea cols=52 name="memo" placeholder="作業内容についての補足など" rows=2></textarea>
                    </td>
                </tr>
                <tr>
                    <th>時間：</th>
                    <td>
                        <select name="task">
                            <option value={{ schedule.task.id}} selected hidden>{{ schedule.task.title }}</option>
                            {% for task in tasks %}
                            <option value={{ task.id }} {%if>{{ task.title }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="button_group">
                            <button class="button update">
                                <input type="submit" value="更新">
                            </button>
                            <button class="button reset">
                                <a href="{% url 'schedules:update' schedule.id %}">reset</a>
                            </button>
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <button class="button link">
        <a href="{% url 'schedules:index' %}">スケジュール一覧へ戻る</a>
    </button>
</main>
</body>
</html>